name = "facil_io_demo"
version = "0.1.0"
description = "Example Gleam project that wraps a facil.io HTTP server"
target = "native"

[dependencies]
gleam_stdlib = { path = "../../../gleam-stdlib" }

[dev-dependencies]

[cranelift]
linker-args = ["native/build/libfacil_io_demo.a"]

[cranelift.targets."aarch64-apple-darwin"]
linker-args = ["-framework", "Security"]
