name = "facil_io"
version = "0.1.0"
description = "Example Gleam project that wraps a facil.io HTTP server"
target = "native"

[dependencies]
gleam_stdlib = { path = "../../../gleam-stdlib" }

[dev-dependencies]

[cranelift]
search-paths = ["native/build"]

[cranelift.targets."aarch64-apple-darwin"]
linker-args = ["-framework", "Security"]
